name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

env:
    FOUNDRY_PROFILE: ci

jobs:
    check:
        strategy:
            fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Show Forge version
              run: |
                  forge --version

    verify-proofs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install ZoKrates
              run: |
                  curl -LSs https://raw.githubusercontent.com/Zokrates/ZoKrates/master/install.sh | sh
                  echo "$(pwd)/zokrates" >> $GITHUB_PATH

            - name: Run correct proof verification
              run: |
                  cd test/correctProof/
                  zokrates verify | tee result.txt
                  grep -q "PASSED" result.txt

            - name: Run corrupted proof verification (expected to fail)
              run: |
                  cd test/corruptedProof/
                  ! zokrates verify | tee result.txt || grep -q "FAILED" result.txt
